// Banco de piadas rápidas para o card "Piada do Momento" da barra inferior.
// 300+ piadas curtas, leves e de bom gosto.
export const PIADAS: string[] = [
  'Por que o livro de matemática estava triste? Porque tinha muitos problemas.',
  'O que o zero disse para o oito? Belo cinto!',
  'Por que a plantinha não foi à escola? Porque já tinha raízes.',
  'O que é um pontinho amarelo no céu? Um Pingo de Luz... voando.',
  'Qual é o cúmulo da paciência? Esperar o ponto de ônibus que já passou.',
  'O que o pato disse para a pata? Vem Quá!',
  'Por que o jacaré tirou a roupa? Porque ele queria ficar à vontade no lago.',
  'Qual é o animal mais antigo? A zebra, porque é em preto e branco.',
  'O que a impressora falou para a outra? Essa folha é sua ou é impressão minha?',
  'Por que o computador foi ao médico? Porque estava com vírus.',
  'O que o tomate foi fazer no banco? Foi tirar extrato.',
  'Por que a vaca foi para o espaço? Para visitar a Via Láctea.',
  'O que o café disse para o açúcar? Sem você minha vida é amarga.',
  'Qual o contrário de volátil? Vem cá, tio.',
  'O que é que tem na geladeira e não congela? A luzinha.',
  'Por que o pão não pode dirigir? Porque ele só faz farinha.',
  'Qual é o doce preferido do átomo? Pé de moleque, porque tem prótons.',
  'O que o pneu falou para o outro? A vida roda.',
  'Por que o esqueleto não brigou? Porque não tinha estômago para isso.',
  'O que a parede disse para a outra? A gente se encontra na esquina.',
  'Por que a abelha não foi presa? Porque pagou fiança com mel.',
  'O que o oceano disse para a praia? Nada, só acenou.',
  'Por que o relógio foi ao psicólogo? Porque o tempo todo dava corda nele.',
  'O que o sal disse para a comida? Eu sou de pegada forte.',
  'Qual é o fim da picada? Quando o mosquito vai embora.',
  'Por que o livro de história nunca dorme? Porque está cheio de datas.',
  'O que o garfo disse para a faca? Você é muito afiada para mim.',
  'Por que o limão é tão sério? Porque é muito azedo nas piadas.',
  'O que o despertador disse de manhã? Levanta que o dia já começou.',
  'Qual é o cúmulo do eletricista? Não ter energia para nada.',
  'O que a nuvem carregou no celular? Dados, claro.',
  'Por que o tijolo foi promovido? Porque ele segura a obra.',
  'O que o sapato falou para a meia? Sem você eu não vou a lugar nenhum.',
  'Por que a tartaruga não usa celular? Porque ela já é lenta o suficiente.',
  'O que o vento disse para a janela? Posso entrar?',
  'Qual é a fruta que mais reclama? A mexerica, porque vive descascada.',
  'Por que a lâmpada teve uma ideia? Porque acendeu na hora certa.',
  'O que o trovão disse para o relâmpago? Você brilha mais que eu.',
  'Por que o jornal foi preso? Porque deu muita notícia furada.',
  'O que a cebola sentiu no cinema? Vontade de chorar.',
  'Qual é o melhor dia para ir à praia? Sol-segunda.',
  'O que o teclado disse para o mouse? Você é muito ágil nas decisões.',
  'Por que o queijo não joga futebol? Porque ele é meio mussarela.',
  'O que a panela disse para a tampa? Você combina comigo.',
  'Por que o astronauta terminou o namoro? Porque precisava de espaço.',
  'O que o microfone disse para a caixa de som? Te escuto em alto e bom som.',
  'Por que o feijão ficou nervoso? Porque entrou na panela de pressão.',
  'O que a vassoura disse para o rodo? Vamos varrer essa sujeira juntos.',
  'Qual é o cúmulo da rapidez? Apagar a luz e deitar antes de escurecer.',
  'O que o celular disse na bateria? Estou sem energia para te aturar.',
  'Por que a girafa demora a responder? Porque a informação leva tempo pra subir.',
  'O que o chá disse para o bule? Você me esquenta.',
  'Por que o ovo não conta piada? Porque pode quebrar no meio.',
  'O que o sofá disse para a almofada? Pode contar comigo pra relaxar.',
  'Qual é o pássaro mais elegante? O pavão, porque sempre se exibe.',
  'O que a chave disse para a fechadura? Você abre meu coração.',
  'Por que a banana foi ao médico? Porque não estava se sentindo madura.',
  'O que o lápis disse para a borracha? Você apaga meus erros.',
  'Por que o trem nunca está atrasado para ele mesmo? Porque ele segue nos trilhos.',
  'O que a estrela disse para a lua? Você ilumina minhas noites.',
  'Qual é o cúmulo do jardineiro? Ficar de mal com a planta.',
  'O que o guarda-chuva disse na chuva? Eu te protejo.',
  'Por que o número par é tão calmo? Porque ele sempre se divide bem.',
  'O que a água disse para o gelo? Relaxa, você já foi como eu.',
  'Por que a formiga não usa elevador? Porque sobe pela parede mesmo.',
  'O que o ventilador disse no calor? Conte comigo.',
  'Qual é o cúmulo da preguiça? Cochilar enquanto boceja.',
  'O que a colher disse para o açúcar? Vamos adoçar o dia.',
  'Por que a maçã caiu? Porque queria conhecer Newton.',
  'O que o copo disse para a jarra? Você me completa.',
  'Por que o sapo é bom de finanças? Porque ele sempre economiza energia pulando.',
  'O que a cama disse de manhã? Fica mais um pouquinho.',
  'Qual é o time preferido do fantasma? O Botafogo, porque assusta.',
  'O que o sol disse para a terra? Você gira em torno de mim.',
  'Por que o pão de queijo é mineiro? Porque é uai-fi de verdade.',
  'O que a folha disse para a árvore? Obrigado por me segurar.',
  'Por que a pipa é feliz? Porque ela vive nas alturas.',
  'O que o fogo disse para a lenha? Você me acende.',
  'Qual é o cúmulo do pintor? Pintar o sete sem tinta.',
  'O que a tinta disse para o pincel? Você espalha minhas cores.',
  'Por que a coruja é sábia? Porque fica acordada estudando.',
  'O que o açaí disse no verão? Eu refresco seu dia.',
  'Por que a estrada nunca se cansa? Porque ela leva a vida com calma.',
  'O que o violão disse para a corda? Você me faz vibrar.',
  'Qual é o cúmulo do padeiro? Sovar a massa e perder a paciência.',
  'O que a montanha disse para o vale? Eu te dou altura.',
  'Por que o caracol carrega a casa? Porque não confia em aluguel.',
  'O que a chuva disse para a terra? Vou te molhar de carinho.',
  'Por que o gato gosta de teclado? Porque adora teclas quentinhas.',
  'O que a porta disse para a janela? A gente se completa na casa.',
  'Qual é o cúmulo da gentileza? Pedir desculpa ao espelho por chegar feio.',
  'O que o sino disse na igreja? Vou dar o toque.',
  'Por que a pizza foi ao psicólogo? Porque estava se sentindo dividida.',
  'O que o leite disse para o café? Vamos clarear esse dia.',
  'Por que a régua é tão certinha? Porque ela mede as palavras.',
  'O que a estrela cadente disse? Faça um pedido rápido.',
  'Qual é o cúmulo do alpinista? Subir pelas paredes de raiva.',
  'O que o relógio de sol disse? Sem luz eu não trabalho.',
  'Por que o peixe não gosta de internet? Porque vive caindo na rede.',
  'O que a vela disse no apagão? Conte comigo.',
  'Por que o limão azedo nunca briga? Porque ele já é amargo demais.',
  'O que a chave de fenda disse? Vou apertar essa amizade.',
  'Qual é o cúmulo do dentista? Ter o nome na ponta da língua dos outros.',
  'O que a bússola disse ao viajante? Siga seu norte.',
  'Por que a lua trabalha à noite? Porque de dia ela tira folga.',
  'O que o espelho disse de manhã? Você está ótimo, confia.',
  'Por que o açúcar não foi à festa? Porque já estava doce demais em casa.',
  'O que a ponte disse para o rio? Eu te atravesso com cuidado.',
  'Qual é o cúmulo do eletricista? Levar um choque de realidade.',
  'O que o trovão fez no show? Soltou o som.',
  'Por que o calendário ficou triste? Porque seus dias estavam contados.',
  'O que a colmeia disse para a abelha? Traga mel pra casa.',
  'Por que a vassoura voa? Porque limpa até no ar.',
  'O que a estrela do mar disse? Eu brilho no fundo.',
  'Qual é o cúmulo da modéstia? Achar humilde ser tão humilde.',
  'O que o farol disse ao navio? Eu te guio.',
  'Por que o pão francês é orgulhoso? Porque ele é crocante por fora.',
  'O que a maçã disse para a banana? Vamos fazer uma salada de amizade.',
  'Por que o gato dorme tanto? Porque ele sonha com sardinha.',
  'O que a flor disse para a abelha? Pode pousar aqui.',
  'Qual é o cúmulo do nadador? Ficar boiando nas ideias.',
  'O que o sabonete disse no banho? Vou deixar você limpinho.',
  'Por que o número um é solitário? Porque não gosta de dividir.',
  'O que a toalha disse depois do banho? Conte comigo pra secar.',
  'Por que a galinha atravessou a rua? Para mostrar ao tatu que dava pra fazer.',
  'O que o despertador disse ao sono? Acabou a moleza.',
  'Qual é o cúmulo do açougueiro? Cortar relações.',
  'O que a chaleira disse? Estou fervendo de vontade.',
  'Por que o caderno foi promovido? Porque tinha boas anotações.',
  'O que a árvore disse ao vento? Pode balançar que eu aguento.',
  'Por que o relógio é educado? Porque ele dá bom dia, boa tarde e boa noite.',
  'O que a panela de pressão disse? Calma, vou explodir de alegria.',
  'Qual é o cúmulo da pressa? Tomar banho de toalha.',
  'O que o leite condensado disse? Vou adoçar tudo.',
  'Por que a tesoura é decidida? Porque ela vai direto ao corte.',
  'O que a cadeira disse? Pode sentar que é de graça.',
  'Por que o vento é fofoqueiro? Porque sopra pra todo lado.',
  'O que a lasanha disse? Eu venho em camadas de carinho.',
  'Qual é o cúmulo do astrônomo? Ver estrelas levando um tropeço.',
  'O que a chuva de verão disse? Sou rápida e refrescante.',
  'Por que o ovo frito é alegre? Porque acorda cedo na frigideira.',
  'O que o ímã disse? Você me atrai.',
  'Por que a girafa é otimista? Porque vê tudo lá de cima.',
  'O que a vela de aniversário disse? Faça seu pedido e me apague.',
  'Qual é o cúmulo do barbeiro? Cortar o assunto.',
  'O que a melancia disse no verão? Sou suculenta de propósito.',
  'Por que a lousa é paciente? Porque aguenta tudo o que escrevem nela.',
  'O que o farol do carro disse? Vou iluminar o caminho.',
  'Por que a pipoca é animada? Porque ela pula de alegria no fogo.',
  'O que a montanha-russa disse? Segura que vem emoção.',
  'Qual é o cúmulo do relojoeiro? Perder a hora.',
  'O que o guarda-sol disse na praia? Eu te protejo do sol.',
  'Por que o suco de laranja é generoso? Porque dá tudo de si.',
  'O que a borboleta disse? Antes eu rastejava, agora eu voo.',
  'Por que a cenoura enxerga bem? Porque ela é cheia de vitamina A.',
  'O que o ventilador disse no inverno? Tô de férias.',
  'Qual é o cúmulo do cozinheiro? Ferver de raiva.',
  'O que a estrela disse no Natal? Vou guiar os reis magos.',
  'Por que o chocolate é querido? Porque derrete corações.',
  'O que a chuva disse para o guarda-chuva? Obrigada por me segurar.',
  'Por que o saci só tem uma perna? Porque a outra ficou pulando.',
  'O que a moeda disse? Sempre tenho dois lados.',
  'Qual é o cúmulo do jardineiro? Plantar bananeira.',
  'O que o sorvete disse no verão? Aproveita antes que eu derreta.',
  'Por que o livro é sábio? Porque guarda o conhecimento.',
  'O que a tampa disse para a garrafa? Vou te fechar com carinho.',
  'Por que o relógio digital é calado? Porque não faz tique-taque.',
  'O que o sino da escola disse? Recreio liberado.',
  'Qual é o cúmulo do fotógrafo? Não tirar nada de letra.',
  'O que a estrela do cinema disse? Luz, câmera, ação.',
  'Por que o mel é doce? Porque a abelha caprichou.',
  'O que a folha de papel disse? Pode escrever sua história em mim.',
  'Por que a coruja usa óculos? Porque lê demais à noite.',
  'O que o trem disse na estação? Próxima parada: aventura.',
  'Qual é o cúmulo do alfaiate? Perder a linha.',
  'O que o café da manhã disse? Comece bem o dia.',
  'Por que a tartaruga ganhou a corrida? Porque a lebre dormiu.',
  'O que o teclado disse para a tela? Eu digito, você mostra.',
  'Por que a chuva é músico? Porque faz uma bela melodia no telhado.',
  'O que o sol disse de manhã? Bom dia, mundo.',
  'Qual é o cúmulo do marinheiro? Ficar boiando nas decisões.',
  'O que o relógio disse à parede? Vou contar as horas pra você.',
  'Por que o queijo ralado é animado? Porque está sempre por cima do macarrão.',
  'O que a lâmpada LED disse? Eu economizo e ilumino.',
  'Por que o cacto é independente? Porque sobrevive sozinho no deserto.',
  'O que a maré disse à praia? Eu vou e volto pra você.',
  'Qual é o cúmulo do piloto? Perder o rumo da conversa.',
  'O que o pãozinho disse na padaria? Estou quentinho pra você.',
  'Por que a estrela pisca? Porque está te dando um oi.',
  'O que a flor disse ao sol? Obrigada por me fazer crescer.',
  'Por que o computador foi à praia? Para esfriar o processador.',
  'O que o despertador disse à cama? Solta ele, já passou da hora.',
  'Qual é o cúmulo do detetive? Perder a pista da própria casa.',
  'O que a chuva disse à plantinha? Crescer com você é um prazer.',
  'Por que a abóbora é alegre no Halloween? Porque adora um sorrisão.',
  'O que o vaga-lume disse? Eu acendo a noite.',
  'Por que o gelo é tímido? Porque derrete fácil.',
  'O que o relâmpago disse? Eu ilumino tudo num instante.',
  'Qual é o cúmulo do músico? Perder o compasso da vida.',
  'O que a janela disse ao sol? Entra que a casa é sua.',
  'Por que a pipoca estoura? Porque não aguenta a pressão.',
  'O que o cobertor disse no frio? Vem que eu te esquento.',
  'Por que o passarinho canta cedo? Porque acorda feliz.',
  'O que a ponte disse aos carros? Passem com cuidado.',
  'Qual é o cúmulo do escritor? Ficar sem palavras.',
  'O que a chuva disse ao arco-íris? Eu te trouxe ao mundo.',
  'Por que a lua some de dia? Porque dá lugar ao sol.',
  'O que o relógio disse no Ano Novo? Hora de recomeçar.',
  'Por que o pão integral é orgulhoso? Porque é cheio de fibra de caráter.',
  'O que o oceano disse ao rio? Bem-vindo de volta.',
  'Qual é o cúmulo do professor? Perder a lição.',
  'O que a vela disse à fósforo? Você me dá luz.',
  'Por que a abelha é trabalhadora? Porque vive no batente.',
  'O que o despertador disse ao café? A gente acorda o mundo juntos.',
  'Por que o livro de piadas é leve? Porque está cheio de risadas.',
  'O que a folha seca disse? Cumpri minha missão.',
  'Qual é o cúmulo do mágico? Sumir com a paciência.',
  'O que a estrela disse ao planeta? Continue na sua órbita.',
  'Por que o sorvete derrete? Porque não aguenta tanto calor de emoção.',
  'O que a chave disse ao cadeado? Só eu te abro.',
  'Por que o relógio cuco é falante? Porque sempre dá um cuco.',
  'O que a maçã disse à árvore? Obrigada por me criar.',
  'Qual é o cúmulo do corredor? Ficar parado de tanto correr atrás.',
  'O que a panela disse ao fogão? Você esquenta minha vida.',
  'Por que o limão faz careta? Porque é azedo até com ele mesmo.',
  'O que o céu disse às estrelas? Brilhem à vontade.',
  'Por que a tartaruga é zen? Porque leva tudo devagar.',
  'O que a lua cheia disse? Hoje eu estou no meu melhor.',
  'Qual é o cúmulo do bombeiro? Apagar a vela de aniversário.',
  'O que o sol disse à lua? A gente se reveza muito bem.',
  'Por que o pão dormiu? Porque ficou de molho na imaginação.',
  'O que a régua disse ao caderno? Vou te deixar nas linhas.',
  'Por que o gato ronrona? Porque está feliz da vida.',
  'O que a estrela disse à constelação? Juntas a gente brilha mais.',
  'Qual é o cúmulo do pescador? Cair na própria rede de mentiras.',
  'O que a chuva disse ao guarda-chuva fechado? Abra-se pra mim.',
  'Por que o feijão é amigo do arroz? Porque eles combinam sempre.',
  'O que o despertador disse no domingo? Hoje eu durmo também.',
  'Por que a borboleta é otimista? Porque sabe que tudo se transforma.',
  'O que o copo cheio disse? Estou transbordando de alegria.',
  'Qual é o cúmulo do relojoeiro? Dar corda em conversa fiada.',
  'O que o livro disse ao leitor? Vire a página comigo.',
  'Por que a estrela do mar é calma? Porque vive no fundo, sem pressa.',
  'O que a chuva fina disse? Sou delicada de propósito.',
  'Por que o sol nasce no leste? Porque gosta de começar pela direita.',
  'O que a vela perfumada disse? Eu deixo o ar com cheirinho bom.',
  'Qual é o cúmulo do carteiro? Perder o endereço de casa.',
  'O que o trovão disse antes da chuva? Já vou avisando.',
  'Por que a melancia é generosa? Porque tem suco pra todo mundo.',
  'O que a montanha disse à neblina? Pode me cobrir de mistério.',
  'Por que o relógio é confiável? Porque nunca perde a hora dele.',
  'O que a abelha rainha disse? Trabalho em equipe é tudo.',
  'Qual é o cúmulo do padeiro? Ficar de mau humor com a fermentação.',
  'O que a estrela disse ao astronauta? Bem-vindo ao meu mundo.',
  'Por que o sorvete de baunilha é discreto? Porque não gosta de chamar atenção.',
  'O que a chave-mestra disse? Eu abro todas as portas.',
  'Por que a lua minguante some aos poucos? Porque está economizando luz.',
  'O que o pãozinho quentinho disse? Aproveita enquanto estou fresco.',
  'Qual é o cúmulo do alfaiate? Costurar uma desculpa esfarrapada.',
  'O que a estrela disse à noite? Sem você eu não brilho.',
  'Por que o café expresso é apressado? Porque vive correndo contra o tempo.',
  'O que a régua disse ao lápis? Vamos fazer linhas retas na vida.',
  'Por que o cão abana o rabo? Porque está contente de te ver.',
  'O que a chuva disse ao campo? Vou te deixar verdinho.',
  'Qual é o cúmulo do astrônomo? Perder a estrela-guia.',
  'O que a panela de arroz disse? Eu deixo tudo soltinho.',
  'Por que o limão siciliano é chique? Porque tem nome de viagem.',
  'O que a montanha disse ao escalador? Suba devagar, a vista vale a pena.',
  'Por que o relógio analógico é elegante? Porque tem estilo clássico.',
  'O que a abelha operária disse? O mel não se faz sozinho.',
  'Qual é o cúmulo do cozinheiro? Ferver na hora errada.',
  'O que a estrela disse ao foguete? Te espero lá em cima.',
  'Por que o sorvete de chocolate é popular? Porque é amado por todos.',
  'O que a chave de ouro disse? Eu encerro com elegância.',
  'Por que a lua nova é misteriosa? Porque a gente nem a vê.',
  'O que o pão de forma disse? Sou prático e quadradinho.',
  'Qual é o cúmulo do jardineiro? Cortar relações com a planta.',
  'O que a estrela disse ao satélite? Continue orbitando comigo.',
  'Por que o café com leite é gentil? Porque equilibra o forte e o suave.',
  'O que a régua dobrável disse? Eu me ajusto a qualquer situação.',
  'Por que o gato sobe na árvore? Porque adora uma vista alta.',
  'O que a chuva torrencial disse? Cheguei com tudo.',
  'Qual é o cúmulo do nadador? Afundar nos pensamentos.',
  'O que a panela elétrica disse? Eu cozinho com inteligência.',
  'Por que o limão tahiti é discreto? Porque é pequeno, mas marcante.',
  'O que a montanha gelada disse? Vista o casaco antes de subir.',
  'Por que o relógio de pulso é companheiro? Porque está sempre com você.',
  'O que a abelha mestre disse? Cada flor tem sua vez.',
  'Qual é o cúmulo do confeiteiro? Perder o ponto da conversa.',
  'O que a estrela disse ao cometa? Você passa rápido demais.',
  'Por que o sorvete de morango é alegre? Porque tem cor de festa.',
  'O que a chave reserva disse? Estou sempre de backup.',
  'Por que a lua de mel é doce? Porque combina amor e açúcar.',
  'O que o pão sírio disse? Sou flexível e prático.',
  'Qual é o cúmulo do paisagista? Não ver a beleza ao redor.',
  'O que a estrela polar disse? Eu nunca te deixo perdido.',
  'Por que o café gelado é despojado? Porque encara o calor de boa.',
  'O que a régua de plástico disse? Sou leve, mas precisa.',
  'Por que o cachorro persegue o próprio rabo? Porque a diversão é gratuita.',
  'O que a chuva da tarde disse? Vou refrescar seu dia.',
  'Qual é o cúmulo do velejador? Ficar à deriva nas próprias dúvidas.',
  'O que a panela de barro disse? Eu cozinho com tradição.',
  'Por que a laranja é solar? Porque tem a cor do sol.',
  'O que a montanha-russa disse aos corajosos? Levanta as mãos.',
  'Por que o relógio de bolso é nostálgico? Porque lembra dos tempos antigos.',
  'O que a abelha jovem disse? Tô aprendendo a fazer mel.',
  'Qual é o cúmulo do chef? Salgar a própria fama.',
  'O que a estrela distante disse? Demoro, mas chego.',
  'Por que o sorvete misto é democrático? Porque agrada todos os sabores.',
  'O que a chave de carro disse? Vamos dar uma volta?',
  'Por que a lua sorri? Porque vê o mundo dormindo em paz.',
  'O que o pão caseiro disse? Fui feito com carinho.',
  'Qual é o cúmulo do horticultor? Perder a raiz do problema.',
  'O que a estrela guia disse aos viajantes? Confiem no caminho.',
  'Por que o café coado é caprichoso? Porque cada gota importa.',
  'O que a régua transparente disse? Comigo nada fica escondido.',
  'Por que o filhote de cachorro é fofo? Porque ainda está aprendendo a latir.',
  'O que a garoa disse à cidade? Vim sem avisar, mas com carinho.',
  'Qual é o cúmulo do capitão? Perder a bússola do bom humor.',
  'O que a panela antiaderente disse? Nada gruda em mim.',
  'Por que o abacaxi é coroado? Porque já nasce com a coroa.',
  'O que o pôr do sol disse? Até amanhã, mundo.',
  'Por que a estrela do amanhecer é a primeira? Porque adora chegar cedo.',
  'O que o travesseiro disse à noite? Pode descansar comigo.',
]
